# Pricing data: USD per 1 million tokens
# Sources: official provider pricing pages + LiteLLM model_prices_and_context_window.json
# Last updated: 2026-05-11 (+ Moonshot AI/Kimi K2; Hyperbolic flat-rate inference)
# Prices may lag behind provider changes — PRs welcome.
# Model IDs match official API identifiers where possible.

MODELS = {
    # ── OpenAI ────────────────────────────────────────────────────────────
    "gpt-4o": {
        "provider": "OpenAI",
        "input_per_mtok": 2.50,
        "output_per_mtok": 10.00,
        "context_window": 128_000,
        "notes": "Latest multimodal flagship",
    },
    "gpt-4o-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 0.15,
        "output_per_mtok": 0.60,
        "context_window": 128_000,
        "notes": "Small, fast, cheap",
    },
    "gpt-4-turbo": {
        "provider": "OpenAI",
        "input_per_mtok": 10.00,
        "output_per_mtok": 30.00,
        "context_window": 128_000,
        "notes": "",
    },
    "gpt-4": {
        "provider": "OpenAI",
        "input_per_mtok": 30.00,
        "output_per_mtok": 60.00,
        "context_window": 8_192,
        "notes": "Original GPT-4 (8k)",
    },
    "gpt-3.5-turbo": {
        "provider": "OpenAI",
        "input_per_mtok": 0.50,
        "output_per_mtok": 1.50,
        "context_window": 16_385,
        "notes": "",
    },
    "o1": {
        "provider": "OpenAI",
        "input_per_mtok": 15.00,
        "output_per_mtok": 60.00,
        "context_window": 200_000,
        "notes": "Reasoning model",
    },
    "o1-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 1.10,
        "output_per_mtok": 4.40,
        "context_window": 128_000,
        "notes": "Fast reasoning model",
    },
    "o3": {
        "provider": "OpenAI",
        "input_per_mtok": 2.00,
        "output_per_mtok": 8.00,
        "context_window": 200_000,
        "notes": "Advanced reasoning (repriced 5× cheaper Apr 2025)",
    },
    "o3-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 1.10,
        "output_per_mtok": 4.40,
        "context_window": 200_000,
        "notes": "Fast advanced reasoning",
    },
    "o4-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 1.10,
        "output_per_mtok": 4.40,
        "context_window": 200_000,
        "notes": "Latest fast reasoning",
    },
    "gpt-4.1": {
        "provider": "OpenAI",
        "input_per_mtok": 2.00,
        "output_per_mtok": 8.00,
        "context_window": 1_047_576,
        "notes": "1M context flagship",
    },
    "gpt-4.1-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 0.40,
        "output_per_mtok": 1.60,
        "context_window": 1_047_576,
        "notes": "1M context, cost-efficient",
    },
    "gpt-4.1-nano": {
        "provider": "OpenAI",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.40,
        "context_window": 1_047_576,
        "notes": "Fastest, cheapest GPT-4.1",
    },
    "gpt-5.5": {
        "provider": "OpenAI",
        "input_per_mtok": 5.00,
        "output_per_mtok": 30.00,
        "context_window": 1_050_000,
        "notes": "OpenAI flagship; 1M context, top coding & reasoning",
    },
    "gpt-5.4": {
        "provider": "OpenAI",
        "input_per_mtok": 2.50,
        "output_per_mtok": 15.00,
        "context_window": 1_050_000,
        "notes": "More affordable GPT-5; 1M context",
    },
    "gpt-5.4-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 0.75,
        "output_per_mtok": 4.50,
        "context_window": 272_000,
        "notes": "Strong mini model; coding, computer use, subagents",
    },
    "gpt-5.4-nano": {
        "provider": "OpenAI",
        "input_per_mtok": 0.20,
        "output_per_mtok": 1.25,
        "context_window": 272_000,
        "notes": "Cheapest GPT-5.4; 272k context",
    },
    "gpt-5-mini": {
        "provider": "OpenAI",
        "input_per_mtok": 0.25,
        "output_per_mtok": 2.00,
        "context_window": 272_000,
        "notes": "Base GPT-5 mini tier",
    },
    "gpt-5-nano": {
        "provider": "OpenAI",
        "input_per_mtok": 0.05,
        "output_per_mtok": 0.40,
        "context_window": 272_000,
        "notes": "Ultra-cheap GPT-5; one of the lowest prices in the dataset",
    },
    "o3-deep-research": {
        "provider": "OpenAI",
        "input_per_mtok": 10.00,
        "output_per_mtok": 40.00,
        "context_window": 200_000,
        "notes": "o3-based deep research; multi-step web + doc research tasks",
    },
    "o4-mini-deep-research": {
        "provider": "OpenAI",
        "input_per_mtok": 2.00,
        "output_per_mtok": 8.00,
        "context_window": 200_000,
        "notes": "Affordable deep research; agentic research loops",
    },
    "gpt-5-codex": {
        "provider": "OpenAI",
        "input_per_mtok": 1.25,
        "output_per_mtok": 10.00,
        "context_window": 272_000,
        "notes": "GPT-5 coding model; 272k context",
    },
    "codex-mini-latest": {
        "provider": "OpenAI",
        "input_per_mtok": 1.50,
        "output_per_mtok": 6.00,
        "context_window": 200_000,
        "notes": "Compact coding model; fast, cost-efficient for code tasks",
    },
    "gpt-5": {
        "provider": "OpenAI",
        "input_per_mtok": 1.25,
        "output_per_mtok": 10.00,
        "context_window": 128_000,
        "notes": "Original GPT-5 release (Aug 2025); 128k ctx",
    },
    "gpt-5.1": {
        "provider": "OpenAI",
        "input_per_mtok": 1.25,
        "output_per_mtok": 10.00,
        "context_window": 128_000,
        "notes": "GPT-5 Nov 2025 update; same price as base GPT-5, improved quality",
    },
    "gpt-5.2": {
        "provider": "OpenAI",
        "input_per_mtok": 1.75,
        "output_per_mtok": 14.00,
        "context_window": 128_000,
        "notes": "GPT-5 Dec 2025 update; improved performance at moderate price premium",
    },
    "gpt-5-pro": {
        "provider": "OpenAI",
        "input_per_mtok": 15.00,
        "output_per_mtok": 120.00,
        "context_window": 272_000,
        "notes": "Premium GPT-5; ultra-high capability; most expensive non-o-series model",
    },
    "o3-pro": {
        "provider": "OpenAI",
        "input_per_mtok": 20.00,
        "output_per_mtok": 80.00,
        "context_window": 200_000,
        "notes": "Professional-grade reasoning; highest o-series capability",
    },
    "o1-pro": {
        "provider": "OpenAI",
        "input_per_mtok": 150.00,
        "output_per_mtok": 600.00,
        "context_window": 200_000,
        "notes": "Ultra-premium reasoning; most expensive model in dataset",
    },
    # ── Anthropic ─────────────────────────────────────────────────────────
    "claude-opus-4-7": {
        "provider": "Anthropic",
        "input_per_mtok": 5.00,
        "output_per_mtok": 25.00,
        "context_window": 1_000_000,
        "notes": "Most capable Claude; 1M context, adaptive thinking",
    },
    "claude-opus-4-6": {
        "provider": "Anthropic",
        "input_per_mtok": 5.00,
        "output_per_mtok": 25.00,
        "context_window": 128_000,
        "notes": "Claude Opus 4.6 (Feb 2026); 128k ctx; same pricing as 4.7",
    },
    "claude-opus-4-5": {
        "provider": "Anthropic",
        "input_per_mtok": 5.00,
        "output_per_mtok": 25.00,
        "context_window": 64_000,
        "notes": "Claude Opus 4.5 (Nov 2025); 64k ctx; mid-cycle revision",
    },
    "claude-opus-4-1": {
        "provider": "Anthropic",
        "input_per_mtok": 15.00,
        "output_per_mtok": 75.00,
        "context_window": 32_000,
        "notes": "Original Claude Opus 4 launch (Aug 2025); expensive legacy tier",
    },
    "claude-sonnet-4-6": {
        "provider": "Anthropic",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 1_000_000,
        "notes": "Best speed/intelligence balance; 1M context",
    },
    "claude-sonnet-4-5": {
        "provider": "Anthropic",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 64_000,
        "notes": "Claude Sonnet 4.5 (Sep 2025); first Sonnet 4 release; 64k ctx",
    },
    "claude-haiku-4-5": {
        "provider": "Anthropic",
        "input_per_mtok": 1.00,
        "output_per_mtok": 5.00,
        "context_window": 200_000,
        "notes": "Fastest Claude 4; near-frontier intelligence",
    },
    "claude-3-7-sonnet": {
        "provider": "Anthropic",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 200_000,
        "notes": "claude-3-7-sonnet-20250219",
    },
    "claude-3-5-sonnet": {
        "provider": "Anthropic",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 200_000,
        "notes": "claude-3-5-sonnet-20241022",
    },
    "claude-3-5-haiku": {
        "provider": "Anthropic",
        "input_per_mtok": 0.80,
        "output_per_mtok": 4.00,
        "context_window": 200_000,
        "notes": "claude-3-5-haiku-20241022",
    },
    "claude-3-opus": {
        "provider": "Anthropic",
        "input_per_mtok": 15.00,
        "output_per_mtok": 75.00,
        "context_window": 200_000,
        "notes": "claude-3-opus-20240229",
    },
    "claude-3-haiku": {
        "provider": "Anthropic",
        "input_per_mtok": 0.25,
        "output_per_mtok": 1.25,
        "context_window": 200_000,
        "notes": "Most affordable Claude 3",
    },
    # ── Google ────────────────────────────────────────────────────────────
    "gemini-3-flash-preview": {
        "provider": "Google",
        "input_per_mtok": 0.50,
        "output_per_mtok": 3.00,
        "context_window": 1_048_576,
        "notes": "Gemini 3 Flash — speed+intelligence with search/grounding; preview",
    },
    "gemini-3.1-pro-preview": {
        "provider": "Google",
        "input_per_mtok": 2.00,
        "output_per_mtok": 12.00,
        "context_window": 1_048_576,
        "notes": "Gemini 3 flagship preview (<=200k pricing); multimodal+agentic",
    },
    "gemini-3.1-flash-lite": {
        "provider": "Google",
        "input_per_mtok": 0.25,
        "output_per_mtok": 1.50,
        "context_window": 1_048_576,
        "notes": "Gemini 3 cost-efficient; high-volume agentic tasks",
    },
    "gemini-deep-research-pro": {
        "provider": "Google",
        "input_per_mtok": 2.00,
        "output_per_mtok": 12.00,
        "context_window": 65_536,
        "notes": "Google Deep Research Pro; multi-step web research; grounding included",
    },
    "gemini-2.5-pro": {
        "provider": "Google",
        "input_per_mtok": 1.25,
        "output_per_mtok": 10.00,
        "context_window": 1_048_576,
        "notes": "State-of-art reasoning/coding; $2.50/$15 for >200k tokens",
    },
    "gemini-2.5-flash": {
        "provider": "Google",
        "input_per_mtok": 0.30,
        "output_per_mtok": 2.50,
        "context_window": 1_048_576,
        "notes": "Hybrid reasoning; 1M context with thinking budgets",
    },
    "gemini-2.5-flash-lite": {
        "provider": "Google",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.40,
        "context_window": 1_048_576,
        "notes": "Smallest/cheapest Gemini 2.5; high-volume at scale",
    },
    "gemini-2.0-flash": {
        "provider": "Google",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.40,
        "context_window": 1_048_576,
        "notes": "Fast, 1M context (deprecated June 2026)",
    },
    "gemini-1.5-pro": {
        "provider": "Google",
        "input_per_mtok": 3.50,
        "output_per_mtok": 10.50,
        "context_window": 2_097_152,
        "notes": "Up to 128k prompt",
    },
    "gemini-1.5-flash": {
        "provider": "Google",
        "input_per_mtok": 0.075,
        "output_per_mtok": 0.30,
        "context_window": 1_048_576,
        "notes": "",
    },
    "gemini-1.5-flash-8b": {
        "provider": "Google",
        "input_per_mtok": 0.0375,
        "output_per_mtok": 0.15,
        "context_window": 1_048_576,
        "notes": "Smallest Gemini",
    },
    # ── Mistral AI ────────────────────────────────────────────────────────
    "magistral-medium": {
        "provider": "Mistral",
        "input_per_mtok": 2.00,
        "output_per_mtok": 5.00,
        "context_window": 40_000,
        "notes": "Mistral's reasoning flagship (Jun 2025); extended thinking, 40k output",
    },
    "magistral-small": {
        "provider": "Mistral",
        "input_per_mtok": 0.50,
        "output_per_mtok": 1.50,
        "context_window": 40_000,
        "notes": "Compact reasoning model; same price as mistral-large-3 but with chain-of-thought",
    },
    "mistral-large-3": {
        "provider": "Mistral",
        "input_per_mtok": 0.50,
        "output_per_mtok": 1.50,
        "context_window": 262_144,
        "notes": "Mistral Large 3 (2512); 4× cheaper than Large 2, 2× context",
    },
    "mistral-large-2": {
        "provider": "Mistral",
        "input_per_mtok": 2.00,
        "output_per_mtok": 6.00,
        "context_window": 128_000,
        "notes": "Mistral Large 2 (2411); superseded by Large 3",
    },
    "mistral-medium-3": {
        "provider": "Mistral",
        "input_per_mtok": 0.40,
        "output_per_mtok": 2.00,
        "context_window": 131_072,
        "notes": "Mistral Medium 3 (2505)",
    },
    "mistral-small-3-2": {
        "provider": "Mistral",
        "input_per_mtok": 0.06,
        "output_per_mtok": 0.18,
        "context_window": 131_072,
        "notes": "Mistral Small 3.2 (2506); 131k context",
    },
    "mistral-small-3": {
        "provider": "Mistral",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.30,
        "context_window": 32_000,
        "notes": "Mistral Small 3 (older, 32k ctx); prefer small-3-2",
    },
    "codestral": {
        "provider": "Mistral",
        "input_per_mtok": 0.30,
        "output_per_mtok": 0.90,
        "context_window": 256_000,
        "notes": "Code-specialized; codestral-2508",
    },
    "devstral-small": {
        "provider": "Mistral",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.30,
        "context_window": 128_000,
        "notes": "Coding agent model; optimized for agentic software engineering tasks",
    },
    "devstral": {
        "provider": "Mistral",
        "input_per_mtok": 0.40,
        "output_per_mtok": 2.00,
        "context_window": 256_000,
        "notes": "Full Devstral coding agent; 256k context for large repos",
    },
    "ministral-3-8b": {
        "provider": "Mistral",
        "input_per_mtok": 0.15,
        "output_per_mtok": 0.15,
        "context_window": 262_144,
        "notes": "Ministral 3 8B; ultra-cheap, 262k ctx, same in/out price",
    },
    "open-mistral-7b": {
        "provider": "Mistral",
        "input_per_mtok": 0.25,
        "output_per_mtok": 0.25,
        "context_window": 32_000,
        "notes": "Open-weights, via API",
    },
    # ── Meta / Llama (via Groq) ───────────────────────────────────────────
    "llama-4-scout": {
        "provider": "Groq",
        "input_per_mtok": 0.11,
        "output_per_mtok": 0.34,
        "context_window": 131_072,
        "notes": "Llama 4 Scout, via Groq API",
    },
    "llama-4-maverick": {
        "provider": "Groq",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.60,
        "context_window": 131_072,
        "notes": "Llama 4 Maverick, via Groq API",
    },
    "llama-3.3-70b": {
        "provider": "Groq",
        "input_per_mtok": 0.59,
        "output_per_mtok": 0.79,
        "context_window": 128_000,
        "notes": "Via Groq API",
    },
    "llama-3.1-8b": {
        "provider": "Groq",
        "input_per_mtok": 0.05,
        "output_per_mtok": 0.08,
        "context_window": 128_000,
        "notes": "Via Groq API",
    },
    "llama-3.1-70b": {
        "provider": "Groq",
        "input_per_mtok": 0.59,
        "output_per_mtok": 0.79,
        "context_window": 128_000,
        "notes": "Via Groq API",
    },
    "kimi-k2-gq": {
        "provider": "Groq",
        "input_per_mtok": 1.00,
        "output_per_mtok": 3.00,
        "context_window": 262_144,
        "notes": "Moonshot Kimi K2 on Groq; 262k context; also on Together/Fireworks",
    },
    "qwen3-32b-gq": {
        "provider": "Groq",
        "input_per_mtok": 0.29,
        "output_per_mtok": 0.59,
        "context_window": 131_000,
        "notes": "Qwen3 32B on Groq; also on Cerebras, Together",
    },
    "gpt-oss-120b-gq": {
        "provider": "Groq",
        "input_per_mtok": 0.15,
        "output_per_mtok": 0.60,
        "context_window": 131_072,
        "notes": "OpenAI open-source 120B on Groq; also on Fireworks/Together/DeepInfra",
    },
    "gpt-oss-20b-gq": {
        "provider": "Groq",
        "input_per_mtok": 0.075,
        "output_per_mtok": 0.30,
        "context_window": 131_072,
        "notes": "OpenAI open-source 20B on Groq; cheaper tier of gpt-oss",
    },
    # ── Cohere ────────────────────────────────────────────────────────────
    "command-a": {
        "provider": "Cohere",
        "input_per_mtok": 2.50,
        "output_per_mtok": 10.00,
        "context_window": 256_000,
        "notes": "Command A (Mar 2025); 256k ctx; enterprise instruction-following; replaces Command R+",
    },
    "command-r-plus": {
        "provider": "Cohere",
        "input_per_mtok": 2.50,
        "output_per_mtok": 10.00,
        "context_window": 128_000,
        "notes": "RAG-optimized",
    },
    "command-r": {
        "provider": "Cohere",
        "input_per_mtok": 0.15,
        "output_per_mtok": 0.60,
        "context_window": 128_000,
        "notes": "",
    },
    "command-r7b": {
        "provider": "Cohere",
        "input_per_mtok": 0.0375,
        "output_per_mtok": 0.15,
        "context_window": 128_000,
        "notes": "Smallest Command R",
    },
    # ── DeepSeek ──────────────────────────────────────────────────────────
    "deepseek-chat": {
        "provider": "DeepSeek",
        "input_per_mtok": 0.27,
        "output_per_mtok": 1.10,
        "context_window": 64_000,
        "notes": "DeepSeek-V3",
    },
    "deepseek-v3.2": {
        "provider": "DeepSeek",
        "input_per_mtok": 0.28,
        "output_per_mtok": 0.40,
        "context_window": 163_840,
        "notes": "DeepSeek-V3.2; 163k ctx; supports reasoning; flat-rate output pricing",
    },
    "deepseek-reasoner": {
        "provider": "DeepSeek",
        "input_per_mtok": 0.55,
        "output_per_mtok": 2.19,
        "context_window": 64_000,
        "notes": "DeepSeek-R1 reasoning",
    },
    # ── xAI ───────────────────────────────────────────────────────────────
    "grok-4.3": {
        "provider": "xAI",
        "input_per_mtok": 1.25,
        "output_per_mtok": 2.50,
        "context_window": 1_000_000,
        "notes": "Grok flagship; 1M ctx, low hallucination, agentic tool calling",
    },
    "grok-4.20-reasoning": {
        "provider": "xAI",
        "input_per_mtok": 1.25,
        "output_per_mtok": 2.50,
        "context_window": 2_000_000,
        "notes": "Grok 4 reasoning variant; 2M context window",
    },
    "grok-4-1-fast": {
        "provider": "xAI",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.50,
        "context_window": 2_000_000,
        "notes": "Grok 4.1 fast tier; 2M ctx; reasoning and non-reasoning variants same price",
    },
    "grok-4": {
        "provider": "xAI",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 256_000,
        "notes": "Grok-4 standard (Jul 2025); 256k ctx; predecessor to 4.3 and 4.20",
    },
    "grok-code-fast": {
        "provider": "xAI",
        "input_per_mtok": 0.20,
        "output_per_mtok": 1.50,
        "context_window": 256_000,
        "notes": "Grok coding specialist; ultra-cheap for code tasks; 256k ctx",
    },
    "grok-3": {
        "provider": "xAI",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 131_072,
        "notes": "Previous generation flagship",
    },
    "grok-3-mini": {
        "provider": "xAI",
        "input_per_mtok": 0.30,
        "output_per_mtok": 0.50,
        "context_window": 131_072,
        "notes": "Fast reasoning",
    },
    "grok-3-mini-fast": {
        "provider": "xAI",
        "input_per_mtok": 0.60,
        "output_per_mtok": 4.00,
        "context_window": 131_072,
        "notes": "High-speed reasoning tier; higher output price reflects accelerated compute",
    },
    # ── Together AI ───────────────────────────────────────────────────────
    # Popular open-weight models via Together AI's serverless API
    "qwen3-235b": {
        "provider": "Together",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.60,
        "context_window": 262_144,
        "notes": "Qwen3 235B-A22B; API: Qwen/Qwen3-235B-A22B-Instruct-2507",
    },
    "kimi-k2": {
        "provider": "Together",
        "input_per_mtok": 0.50,
        "output_per_mtok": 2.80,
        "context_window": 262_144,
        "notes": "Moonshot Kimi K2.5; API: moonshotai/Kimi-K2.5",
    },
    "llama-3.3-70b-turbo": {
        "provider": "Together",
        "input_per_mtok": 0.88,
        "output_per_mtok": 0.88,
        "context_window": 131_072,
        "notes": "Same in/out price; API: meta-llama/Llama-3.3-70B-Instruct-Turbo",
    },
    "qwen3.5-9b": {
        "provider": "Together",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.15,
        "context_window": 262_144,
        "notes": "Qwen3.5 9B; API: Qwen/Qwen3.5-9B",
    },
    "deepseek-r1-together": {
        "provider": "Together",
        "input_per_mtok": 3.00,
        "output_per_mtok": 7.00,
        "context_window": 163_840,
        "notes": "DeepSeek-R1-0528; API: deepseek-ai/DeepSeek-R1",
    },
    "deepseek-v3-together": {
        "provider": "Together",
        "input_per_mtok": 0.60,
        "output_per_mtok": 1.70,
        "context_window": 131_072,
        "notes": "DeepSeek-V3.1; API: deepseek-ai/DeepSeek-V3.1",
    },
    "deepseek-v4-pro-together": {
        "provider": "Together",
        "input_per_mtok": 2.10,
        "output_per_mtok": 4.40,
        "context_window": 512_000,
        "notes": "DeepSeek-V4-Pro; API: deepseek-ai/DeepSeek-V4-Pro",
    },
    # ── Fireworks AI ──────────────────────────────────────────────────────
    # Per-model pricing; unnamed models billed by size tier
    "deepseek-v4-pro-fw": {
        "provider": "Fireworks",
        "input_per_mtok": 1.74,
        "output_per_mtok": 3.48,
        "context_window": 512_000,
        "notes": "DeepSeek V4 Pro; API: accounts/fireworks/models/deepseek-v4-pro",
    },
    "deepseek-v3-fw": {
        "provider": "Fireworks",
        "input_per_mtok": 0.56,
        "output_per_mtok": 1.68,
        "context_window": 131_072,
        "notes": "DeepSeek V3 family; API: accounts/fireworks/models/deepseek-v3",
    },
    "kimi-k2-fw": {
        "provider": "Fireworks",
        "input_per_mtok": 0.60,
        "output_per_mtok": 3.00,
        "context_window": 262_144,
        "notes": "Kimi K2.5; API: accounts/fireworks/models/kimi-k2",
    },
    "llama-3.1-70b-fw": {
        "provider": "Fireworks",
        "input_per_mtok": 0.90,
        "output_per_mtok": 0.90,
        "context_window": 131_072,
        "notes": "Llama 3.1 70B (>16B tier, same in/out); API: accounts/fireworks/models/llama-v3p1-70b-instruct",
    },
    "llama-3.1-8b-fw": {
        "provider": "Fireworks",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.20,
        "context_window": 131_072,
        "notes": "Llama 3.1 8B (4B-16B tier, same in/out); API: accounts/fireworks/models/llama-v3p1-8b-instruct",
    },
    "mixtral-8x7b-fw": {
        "provider": "Fireworks",
        "input_per_mtok": 0.50,
        "output_per_mtok": 0.50,
        "context_window": 32_768,
        "notes": "Mixtral 8x7B MoE; API: accounts/fireworks/models/mixtral-8x7b-instruct",
    },
    # ── Perplexity AI ─────────────────────────────────────────────────────
    # Sonar models include web search; extra $0.005/request fee for search queries
    "sonar": {
        "provider": "Perplexity",
        "input_per_mtok": 1.00,
        "output_per_mtok": 1.00,
        "context_window": 127_072,
        "notes": "Web-search grounded; +$0.005/request fee",
    },
    "sonar-pro": {
        "provider": "Perplexity",
        "input_per_mtok": 3.00,
        "output_per_mtok": 15.00,
        "context_window": 200_000,
        "notes": "Pro web-search grounded; +$0.005/request fee",
    },
    "sonar-reasoning-pro": {
        "provider": "Perplexity",
        "input_per_mtok": 2.00,
        "output_per_mtok": 8.00,
        "context_window": 128_000,
        "notes": "Reasoning + search; +$0.005/request fee",
    },
    "sonar-deep-research": {
        "provider": "Perplexity",
        "input_per_mtok": 2.00,
        "output_per_mtok": 8.00,
        "context_window": 128_000,
        "notes": "Multi-step research; +$5/1K search queries",
    },
    # ── Cerebras ──────────────────────────────────────────────────────────
    # Ultra-fast inference on custom Cerebras silicon (wafer-scale chips)
    # Pricing: https://cerebras.ai/pricing  Source: LiteLLM model_prices_and_context_window.json
    "llama-3.3-70b-cb": {
        "provider": "Cerebras",
        "input_per_mtok": 0.85,
        "output_per_mtok": 1.20,
        "context_window": 128_000,
        "notes": "Llama 3.3 70B; ultra-fast Cerebras inference",
    },
    "llama-3.1-8b-cb": {
        "provider": "Cerebras",
        "input_per_mtok": 0.10,
        "output_per_mtok": 0.10,
        "context_window": 128_000,
        "notes": "Llama 3.1 8B; ultra-cheap, ultra-fast on Cerebras",
    },
    "qwen3-32b-cb": {
        "provider": "Cerebras",
        "input_per_mtok": 0.40,
        "output_per_mtok": 0.80,
        "context_window": 128_000,
        "notes": "Qwen3 32B on Cerebras silicon",
    },
    # ── SambaNova ─────────────────────────────────────────────────────────
    # Ultra-fast inference on SambaNova RDU (Reconfigurable Dataflow Unit) silicon
    # Pricing: https://api.sambanova.ai/v1/models (live API, no auth required)
    "llama-4-maverick-sb": {
        "provider": "SambaNova",
        "input_per_mtok": 0.63,
        "output_per_mtok": 1.80,
        "context_window": 131_072,
        "notes": "Meta Llama 4 Maverick 17B-128E; SambaNova RDU fast inference",
    },
    "llama-3.3-70b-sb": {
        "provider": "SambaNova",
        "input_per_mtok": 0.60,
        "output_per_mtok": 1.20,
        "context_window": 131_072,
        "notes": "Llama 3.3 70B on SambaNova RDU",
    },
    "deepseek-v3-sb": {
        "provider": "SambaNova",
        "input_per_mtok": 3.00,
        "output_per_mtok": 4.50,
        "context_window": 131_072,
        "notes": "DeepSeek-V3.1 on SambaNova; 131k context",
    },
    "minimax-m2-5-sb": {
        "provider": "SambaNova",
        "input_per_mtok": 0.30,
        "output_per_mtok": 1.20,
        "context_window": 163_840,
        "notes": "MiniMax M2.5; 160k context window",
    },
    "gemma-3-12b-sb": {
        "provider": "SambaNova",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.35,
        "context_window": 131_072,
        "notes": "Google Gemma 3 12B on SambaNova RDU",
    },
    # ── Amazon Bedrock ────────────────────────────────────────────────────
    # Amazon's own Nova foundation models, on-demand pricing (US East, N. Virginia)
    # Source: LiteLLM + https://aws.amazon.com/bedrock/pricing/
    "nova-micro-br": {
        "provider": "Bedrock",
        "input_per_mtok": 0.035,
        "output_per_mtok": 0.14,
        "context_window": 128_000,
        "notes": "Amazon Nova Micro; text-only, lowest latency, cheapest Nova",
    },
    "nova-lite-br": {
        "provider": "Bedrock",
        "input_per_mtok": 0.06,
        "output_per_mtok": 0.24,
        "context_window": 300_000,
        "notes": "Amazon Nova Lite; multimodal (text/image/video), 300k ctx",
    },
    "nova-pro-br": {
        "provider": "Bedrock",
        "input_per_mtok": 0.80,
        "output_per_mtok": 3.20,
        "context_window": 300_000,
        "notes": "Amazon Nova Pro; strongest Nova for complex tasks, 300k ctx",
    },
    "nova-premier-br": {
        "provider": "Bedrock",
        "input_per_mtok": 2.50,
        "output_per_mtok": 12.50,
        "context_window": 1_000_000,
        "notes": "Amazon Nova Premier; top-tier, 1M token context",
    },
    "nova-2-lite-br": {
        "provider": "Bedrock",
        "input_per_mtok": 0.30,
        "output_per_mtok": 2.50,
        "context_window": 1_000_000,
        "notes": "Amazon Nova 2 Lite; 1M context, more capable than Nova Lite",
    },
    # ── AI21 Labs ─────────────────────────────────────────────────────────
    # Jamba = hybrid SSM (Mamba) + Transformer; 256k context at low cost
    # Pricing: https://www.ai21.com/pricing  (AI21 claims ~30% more text/token vs peers)
    "jamba-mini-a21": {
        "provider": "AI21",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.40,
        "context_window": 256_000,
        "notes": "Jamba Mini 1.7; 256k ctx, hybrid SSM+Transformer architecture",
    },
    "jamba-large-a21": {
        "provider": "AI21",
        "input_per_mtok": 2.00,
        "output_per_mtok": 8.00,
        "context_window": 256_000,
        "notes": "Jamba Large 1.7; 256k ctx, flagship Jamba model",
    },
    # ── DeepInfra ─────────────────────────────────────────────────────────
    # Inference cloud with competitive open-weight pricing; notable for 1M+ context
    # Source: LiteLLM model_prices_and_context_window.json (deepinfra provider)
    "llama-4-maverick-di": {
        "provider": "DeepInfra",
        "input_per_mtok": 0.15,
        "output_per_mtok": 0.60,
        "context_window": 1_048_576,
        "notes": "Meta Llama 4 Maverick FP8; 1M token context — largest Llama 4 ctx available",
    },
    "llama-4-scout-di": {
        "provider": "DeepInfra",
        "input_per_mtok": 0.08,
        "output_per_mtok": 0.30,
        "context_window": 327_680,
        "notes": "Meta Llama 4 Scout; 327k context, cheapest Scout option",
    },
    "deepseek-r1-0528-di": {
        "provider": "DeepInfra",
        "input_per_mtok": 0.50,
        "output_per_mtok": 2.15,
        "context_window": 163_840,
        "notes": "DeepSeek-R1-0528; latest R1 update on DeepInfra",
    },
    "qwq-32b-di": {
        "provider": "DeepInfra",
        "input_per_mtok": 0.15,
        "output_per_mtok": 0.40,
        "context_window": 131_072,
        "notes": "Qwen QwQ-32B reasoning model; strong math/code reasoning",
    },
    # ── Lambda AI ─────────────────────────────────────────────────────────
    # On-demand GPU inference; notable for ultra-cheap Llama 4 pricing
    # Source: LiteLLM model_prices_and_context_window.json (lambda_ai provider)
    "llama-4-maverick-la": {
        "provider": "Lambda",
        "input_per_mtok": 0.05,
        "output_per_mtok": 0.10,
        "context_window": 131_072,
        "notes": "Meta Llama 4 Maverick FP8 on Lambda; tied with gpt-5-nano as cheapest capable model",
    },
    "llama-4-scout-la": {
        "provider": "Lambda",
        "input_per_mtok": 0.05,
        "output_per_mtok": 0.10,
        "context_window": 16_384,
        "notes": "Meta Llama 4 Scout on Lambda; ultra-cheap, 16k ctx",
    },
    "llama3.3-70b-la": {
        "provider": "Lambda",
        "input_per_mtok": 0.12,
        "output_per_mtok": 0.30,
        "context_window": 131_072,
        "notes": "Llama 3.3 70B FP8 on Lambda",
    },
    "deepseek-r1-0528-la": {
        "provider": "Lambda",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.60,
        "context_window": 131_072,
        "notes": "DeepSeek-R1-0528 on Lambda; very cheap reasoning model",
    },
    # ── Novita AI ─────────────────────────────────────────────────────────
    # Inference marketplace with competitive pricing on open-weight models
    # Source: LiteLLM model_prices_and_context_window.json (novita provider)
    "llama-4-maverick-no": {
        "provider": "Novita",
        "input_per_mtok": 0.27,
        "output_per_mtok": 0.85,
        "context_window": 1_048_576,
        "notes": "Llama 4 Maverick FP8 on Novita; 1M context",
    },
    "llama-4-scout-no": {
        "provider": "Novita",
        "input_per_mtok": 0.18,
        "output_per_mtok": 0.59,
        "context_window": 131_072,
        "notes": "Llama 4 Scout on Novita",
    },
    "deepseek-r1-0528-no": {
        "provider": "Novita",
        "input_per_mtok": 0.70,
        "output_per_mtok": 2.50,
        "context_window": 163_840,
        "notes": "DeepSeek-R1-0528 on Novita; latest reasoning model",
    },
    "qwen3-235b-no": {
        "provider": "Novita",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.80,
        "context_window": 40_000,
        "notes": "Qwen3 235B-A22B FP8 on Novita; flagship Qwen3 MoE",
    },

    # ── Nebius AI ─────────────────────────────────────────────────────────
    # Source: LiteLLM model_prices_and_context_window.json (nebius provider)
    # Nebius: European AI cloud, H100/H200 GPUs, competitive prices for open models
    "llama-3.1-8b-nb": {
        "provider": "Nebius",
        "input_per_mtok": 0.02,
        "output_per_mtok": 0.06,
        "context_window": 128_000,
        "notes": "Llama 3.1 8B on Nebius; cheapest Llama 3.1 8B available",
    },
    "llama-3.3-70b-nb": {
        "provider": "Nebius",
        "input_per_mtok": 0.13,
        "output_per_mtok": 0.40,
        "context_window": 128_000,
        "notes": "Llama 3.3 70B on Nebius",
    },
    "qwen3-235b-nb": {
        "provider": "Nebius",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.60,
        "context_window": 262_144,
        "notes": "Qwen3 235B-A22B on Nebius; 262k context",
    },
    "nemotron-ultra-253b-nb": {
        "provider": "Nebius",
        "input_per_mtok": 0.60,
        "output_per_mtok": 1.80,
        "context_window": 128_000,
        "notes": "Nvidia Llama-3.1-Nemotron-Ultra-253B on Nebius; 253B research model",
    },
    "deepseek-r1-0528-nb": {
        "provider": "Nebius",
        "input_per_mtok": 0.80,
        "output_per_mtok": 2.40,
        "context_window": 164_000,
        "notes": "DeepSeek-R1-0528 on Nebius; 164k context",
    },

    # ── Moonshot AI (Kimi) ────────────────────────────────────────────────
    # Source: LiteLLM model_prices_and_context_window.json (moonshot provider)
    # Moonshot AI: Chinese AI lab; Kimi K2 is their 2026 flagship MoE model
    "kimi-k2-mk": {
        "provider": "Moonshot",
        "input_per_mtok": 0.60,
        "output_per_mtok": 2.50,
        "context_window": 131_072,
        "notes": "Kimi K2 0711 preview; flagship MoE, 131k context",
    },
    "kimi-k2-thinking-mk": {
        "provider": "Moonshot",
        "input_per_mtok": 0.60,
        "output_per_mtok": 2.50,
        "context_window": 262_144,
        "notes": "Kimi K2 thinking/reasoning mode; 262k context",
    },
    "kimi-k2-thinking-turbo-mk": {
        "provider": "Moonshot",
        "input_per_mtok": 1.15,
        "output_per_mtok": 8.00,
        "context_window": 262_144,
        "notes": "Kimi K2 turbo thinking; fastest reasoning variant; 262k context",
    },
    "moonshot-v1-8k-mk": {
        "provider": "Moonshot",
        "input_per_mtok": 0.20,
        "output_per_mtok": 2.00,
        "context_window": 8_192,
        "notes": "Moonshot V1 short-context; cheapest Moonshot entry point",
    },
    "moonshot-v1-128k-mk": {
        "provider": "Moonshot",
        "input_per_mtok": 2.00,
        "output_per_mtok": 5.00,
        "context_window": 131_072,
        "notes": "Moonshot V1 full 128k context; general-purpose",
    },

    # ── Hyperbolic ────────────────────────────────────────────────────────
    # Source: LiteLLM model_prices_and_context_window.json (hyperbolic provider)
    # Hyperbolic: US inference provider; notable for flat input=output pricing on some models
    "deepseek-r1-0528-hy": {
        "provider": "Hyperbolic",
        "input_per_mtok": 0.25,
        "output_per_mtok": 0.25,
        "context_window": 131_072,
        "notes": "DeepSeek-R1-0528 on Hyperbolic; flat $0.25 in=out; cheapest R1-0528",
    },
    "deepseek-v3-0324-hy": {
        "provider": "Hyperbolic",
        "input_per_mtok": 0.40,
        "output_per_mtok": 0.40,
        "context_window": 32_768,
        "notes": "DeepSeek-V3-0324 on Hyperbolic; flat rate pricing",
    },
    "llama-3.3-70b-hy": {
        "provider": "Hyperbolic",
        "input_per_mtok": 0.12,
        "output_per_mtok": 0.30,
        "context_window": 131_072,
        "notes": "Llama 3.3 70B on Hyperbolic",
    },
    "llama-3.1-405b-hy": {
        "provider": "Hyperbolic",
        "input_per_mtok": 0.12,
        "output_per_mtok": 0.30,
        "context_window": 32_768,
        "notes": "Llama 3.1 405B on Hyperbolic; massive model at competitive price",
    },
    "kimi-k2-hy": {
        "provider": "Hyperbolic",
        "input_per_mtok": 2.00,
        "output_per_mtok": 2.00,
        "context_window": 131_072,
        "notes": "Kimi K2 on Hyperbolic; flat in=out rate",
    },

    # ── Crusoe ────────────────────────────────────────────────────────────
    # Source: LiteLLM model_prices_and_context_window.json (crusoe provider)
    # Crusoe: US GPU cloud; notable for gpt-oss-120b (OpenAI open-source 120B)
    # and flat input=output pricing on most models
    "gpt-oss-120b-cr": {
        "provider": "Crusoe",
        "input_per_mtok": 0.80,
        "output_per_mtok": 0.80,
        "context_window": 131_072,
        "notes": "OpenAI open-source 120B on Crusoe; flat rate; 131k context",
    },
    "llama-3.3-70b-cr": {
        "provider": "Crusoe",
        "input_per_mtok": 0.20,
        "output_per_mtok": 0.20,
        "context_window": 131_072,
        "notes": "Llama 3.3 70B on Crusoe; flat rate",
    },
    "deepseek-v3-0324-cr": {
        "provider": "Crusoe",
        "input_per_mtok": 1.50,
        "output_per_mtok": 1.50,
        "context_window": 163_840,
        "notes": "DeepSeek-V3-0324 on Crusoe; flat rate; 163k context",
    },
    "kimi-k2-thinking-cr": {
        "provider": "Crusoe",
        "input_per_mtok": 2.50,
        "output_per_mtok": 2.50,
        "context_window": 262_144,
        "notes": "Kimi K2 Thinking on Crusoe; flat rate; 262k context",
    },
    "deepseek-r1-0528-cr": {
        "provider": "Crusoe",
        "input_per_mtok": 3.00,
        "output_per_mtok": 7.00,
        "context_window": 163_840,
        "notes": "DeepSeek-R1-0528 on Crusoe; 163k context",
    },
}

PROVIDERS = sorted({m["provider"] for m in MODELS.values()})
DATA_DATE = "2026-05-11"
